# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_emails: angry_admin@mail.com
  domain_name: localhost:3000
  gmail_username: ourstartups.loc
  gmail_password: brightidea777
  secret_key_base: 23452daf7a9514478b75faa498f88cfdef723837253e3c0d16b23e6d769cf518d5b8de9520c73b5221cfa724439e1fba2e0084a77eb2e57ecae101ab9d71cc1c

test:
  secret_key_base: 83e33f20b85a6a6c8080b9a3a7e400fff824276a249c4113f51d287c7280794d1803be80b023e92f566f62a9b9c27325112d35287ad1a47938c02ee3d87f82d8

staging:
  admin_emails: angry_admin@mail.com
  domain_name: our-startups-st.loc
  gmail_username: ourstartups.loc
  gmail_password: brightidea777
  secret_key_base: de085679e723468b9c5be518b0c85609d052ab8cd00c7975d263a0831434dd8068d50e50386edb566da555186bcf673314a925d4862b34b6062b0dac45912732

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
